# Generated by Django 4.1.5 on 2023-02-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, default='/holder.jpeg', null=True, upload_to='Posted_Images'),
        ),
    ]
